### ISSUE TITLE
Notice of NO affiliation to Prepay Nation LLC

### ISSUE THREAD

**Issue by wpurna** [ynloultratech/pepaynation-api#1]
Hi,

I work for Prepay Nation LLC and I would like to request you to add a disclaimer that this library and the code is not endorsed by or affiliated to Prepay Nation LLC. I understand that this is your personal code but it is creating confusion amongst our other customers while implementing the API.

Please clarify in the documentation that this is your implementation and has no direct relation with Prepay Nation API.

Thank you!

support@prepaynation.com

**Comment by omynomyn** [comment]
Done!

**Comment by wpurna** [comment]
Great! Thank you!

**Comment by omynomyn** [comment]
Hi Purna:

 

Sorry for that, that repository supposed to be a private, any ways I just added the disclaimer, let me know if you need anything else from our end and we will more than happy to do it.

 

Thx

Octavio
